'use strict';

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  USER: 'USER',
};

const EVENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const APPLICATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
};

const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

const TRANSACTION_TYPE = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
};

const ATTENDANCE_STATUS = {
  CHECKED_IN: 'CHECKED_IN',
  CHECKED_OUT: 'CHECKED_OUT',
  ABSENT: 'ABSENT',
};

const TASK_STATUS = {
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
};

const ISSUE_TYPE = {
  NO_SHOW: 'NO_SHOW',
  MISCONDUCT: 'MISCONDUCT',
  PERFORMANCE: 'PERFORMANCE',
  OTHER: 'OTHER',
};

const NOTIFICATION_TYPE = {
  APPLICATION_ACCEPTED: 'APPLICATION_ACCEPTED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  PAYMENT_RELEASED: 'PAYMENT_RELEASED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  EVENT_REMINDER: 'EVENT_REMINDER',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
};

const REDIS_KEYS = {
  OTP: (phone) => `otp:${phone}`,
  OTP_ATTEMPTS: (phone) => `otp:attempts:${phone}`,
  OTP_BLOCKED: (phone) => `otp:blocked:${phone}`,
  OTP_RATE: (phone) => `otp:rate:${phone}`,
  OTP_VERIFIED: (phone) => `otp:verified:${phone}`,
  REFRESH_TOKEN: (userId, role) => `refresh:${role}:${userId}`,
  EVENT_CACHE: (eventId) => `event:${eventId}`,
  ADMIN_EVENTS: (adminId) => `admin:events:${adminId}`,
};

module.exports = {
  ROLES,
  EVENT_STATUS,
  APPLICATION_STATUS,
  VERIFICATION_STATUS,
  PAYMENT_STATUS,
  TRANSACTION_TYPE,
  ATTENDANCE_STATUS,
  TASK_STATUS,
  ISSUE_TYPE,
  NOTIFICATION_TYPE,
  REDIS_KEYS,
};
